# Generated by Django 4.0 on 2021-12-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_b4sh5i_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b4sh5i_data',
            name='updated_at',
        ),
    ]
